# streamlit_app/resources/resources.py

# File contains all the long list data to support app.py

# BehavriorCriteria
behaviorcriteria_Description = [
        'Capable of carrying out a given task with all details necessary to get the task done well',
        'Inspires teammates to follow them', 
        'Considered a thought leader on a subject', 
        'Capable of making others think deeply on a subject',
        'Devoted to a task or purpose with loyalty or integrity',
        'Works well as a member of a group',
        'Consistently introduces new ideas and demonstrates original thinking',
        'Shows firm and constant support to a cause',
        'Shows intense and eager enjoyment and interest']

behaviorcriteria_Name = [
        'Detail Oriented', 
        'Thought Provoking', 
        'Loyal', 
        'Innovative', 
        'Dedicated', 
        'Team Player', 
        'Leader',
        'Functional Expert',
        'Enthusiastic'
]
behaviorcriteria_Required = ['false', 'true']

#MotivationCriteria
motivationcriteria_Description = ['Inspired to perform well by monetary reimbursement',
  'Inspired to perform well by the praise of coworkers',
  'Inspired to perform well when granted the ability to set your own schedule and goals',
  'Inspired to perform well by the chance to take on more responsibility',
  'Inspired to perform well by the knowledge that your job is safe',
  'Inspired to perform well by the completion of tasks',
  'Inspired to perform without outside help',
  'Inspired to perform well by an ability to drive new ventures within the business',
  'Inspired to perform well by having ample time to pursue work and interests outside of work',
  'Inspired to perform well by the ability to contribute to the success of a project or the organization']

motivationcriteria_Name = ['Flexibility',
  'Growth Opportunities',
  'Financial',
  'Job Security',
  'Goal Completion',
  'Work-Life Balance',
  'Ability to Make an Impact',
  'Peer Recognition',
  'Self-Starter',
  'Entrepreneurial Spirit']
motivationcriteria_Required = ['false', 'true']

# EducationCriteria

educationcriteria_Related = ['false', 'true']
educationcriteria_Degree =  ['Certification',
  'Bachelors',
  'Associates',
  'Technical/Other Training',
  'Graduate Accre Nurs Prog',
  'Diploma',
  'Cert Respiratory Therapst',
  'Accredited Rad Tech Prog',
  'Masters',
  'Attending',
  'Registered Nurse',
  'Bachelor of Science',
  'High School',
  'HS Diploma',
  'PhD',
  'Accr Sch HistoTech Prog',
  'Associate of Arts',
  'Accr Resp Therapy Program',
  'Reg Respiratory Therapist',
  'Post-Sec Secretarial Crwk',
  'Technical/other training',
  'Some college',
  'Emergency Medical Tech',
  'Bachelor of Arts',
  'Paramedic',
  'Bachelor of Business Admin',
  'Nurse Practitioner',
  'High School/GED',
  'Associates/Equivalent',
  'Doctorate',
  'HS Diploma/Equivalent',
  'Juris Doctor',
  'Licensed Pract Nurse',
  'Bachelors/Equivalent']

educationcriteria_Major = ['ACCOUNTING',
  'BIOLOGY',
  'MEDICAL ASSISTANT',
  'Journalism',
  'Biology or Related Field',
  'Early Childhood Education',
  'Business',
  'Electrical Engineering',
  'EXERCISE & SPORT SCIENCE',
  'HISTOTECHNOLOGY',
  'Real Estate Property Mgmt',
  'Engineering',
  'PSYCHOLOGY',
  'PHYSICAL THERAPY',
  'MEDICAL LAB TECH',
  'SOCIAL WORK',
  'Law',
  'Human Resource Administration',
  'NURSING',
  'Social Work',
  'Marketing',
  'Computer Science',
  'MARKETING',
  'HEALTH SVC ADMINISTRATION',
  'Management Information Systems',
  'Accounting Systems',
  'CODING',
  'MANAGEMENT',
  'Construction Management Services',
  'FINANCE',
  'Accounting or Rel Field',
  'PHLEBOTOMY',
  'No Major',
  'BUSINESS ADMINISTRATION',
  'Business Administration',
  'ELECTRONICS TECHNOLOGY',
  'COMPUTER SCIENCE',
  'RADIOLOGY',
  'FOOD AND NUTRITION',
  'Paralegal Studies',
  'BusinessAdministration',
  'Graphic Design',
  'Advertising',
  'Information Systems',
  'Other',
  'HEALTH SCIENCES',
  'Hospitality and Resort Management',
  'MEDICAL LAB TECHNICIAN',
  'OTHER',
  'Economics',
  'Technology Management Services',
  'DIETETICS',
  'NUCLEAR MEDICINE',
  'Administration',
  'Taxation',
  'HEALTH ADMINISTRATION',
  'Risk Management and Insurance',
  'Finance',
  'Special Education',
  'PHARMACY',
  'Information Technology',
  'BIOTECHNOLOGY',
  'Communication',
  'INFORMATION TECHNOLOGY',
  'Management',
  'Real Estate Development',
  'Accounting',
  'ULTRASOUND',
  'Healthcare Administration',
  'Real Estate',
  'Education',
  None,
  'PARAMEDIC PROGRAM',
  'PHYSICIAN ASSISTANT',
  'Biology',
  'Communications',
  'ENGINEERING',
  'Human Resources',
  'Marketing Management',
  'Construction',
  'ATHLETIC TRAINING',
  'English',
  'RESPIRATORY THERAPY',
  'Computer Engineering',
  'CULINARY MANAGEMENT',
  'Human Services',
  'Mulitple Majors-Rel Field',
  'Business Economics',
  'Logistics /Supply Chain Management',
  'HUMAN RESOURCE ADMIN']

educationcriteria_Required = ['false', 'true']

LicenseAndCertificationCriteria_LicenseAndCertification = ['Cert Public Accountant',
  'EMERGENCY MEDICAL TECH',
  'CERTIFIED DIETARY MANAGER',
  'Certified EE Benefit Spec',
  'REGISTERED NURSE',
  'Sr Professional HR',
  'REGISTERED DIETITIAN',
  'Chartered Fin Analyst',
  'Z_DNU_CDE',
  'DEA',
  'Applicator Branch 2',
  'Certified Apartment Mgr',
  'Licensed Social Worker',
  'EPA Cert/HVAC',
  'First Aid',
  'NIH STROKE SCALE',
  'Board Certified',
  'CERT PROFESSIONAL CODER',
  'NAT COMM CERT PHY ASSIST',
  'PALS',
  'Certified Pool Operator',
  'NUC MED TECH CERT BOARD',
  'Certified Property Mgr',
  'PHARMACIST',
  'AMER REG DX MED SONOGP-VB',
  'Licensed Practical Nurse',
  'Accredited Res. Manager',
  'Group Benefits Associate',
  'REG DIAGNOSTIC CARD SONO',
  'VA Master Mechanical',
  'CT TECH',
  "Driver's License",
  'PMP',
  'NMLS',
  'Professional in HR',
  'PHLEBOTOMY',
  'CMA',
  'BLS (AHA)',
  'CERT NURS ASSISTANT',
  'Cert Healthcare Compl',
  'CCNA',
  'SOCIAL WORKER',
  'PHARMACY TECHNICIAN',
  'Cert Pool Operator',
  'PARAMEDIC',
  'WORKPLACE VIOLENCE PREVEN',
  'CERT PSYCH REHAB PRACT',
  'CISCO',
  'SERVSAFE CERTIFIED',
  'CCIE',
  'AMER REG RAD TECH',
  'Property and Casualty',
  'Driver License',
  'Life Guard',
  'Public Account',
  'MEDICAL LAB TECHNICIAN',
  'OSHA 30',
  'ASCP-LAB',
  'ATHLETIC TRAINER',
  'PHARMD',
  'BLS INSTRUCTOR',
  'WORKPLACE VIOLENCE TRAINR',
  'LISW-Independent Soc Wrkr',
  'PHYSICIANS ASSISTANT',
  'CRNP-CERT',
  'Licnsd Prof Clinical Cou',
  'Commercial Driver License',
  'PROJECT MANAGMENT CERT',
  'Z_DNU-NPDC',
  'CPA',
  'RCIS',
  'RADIOLOGY TECHNOLOGIST',
  'CERT CODING SPECIALIST',
  'MAMMOGRAPHY',
  'HVAC EPA Type II',
  'CERT CODING SPEC PHY BASE',
  'Life and Health',
  'IT',
  'PHYSICAL THERAPIST',
  'CompTIA A+ Cert.',
  'CCNP',
  'Cert Coding Spec - Phys',
  'RESPIRATORY CARE PRACT',
  'ACLS',
  'Certified Financial Mgr',
  'CERTIFIED MEDICAL ASSIST',
  'SHCM',
  'HCCP',
  'Natl Mortg License System',
  'NUCLEAR MEDICINE TECH',
  "DRIVER'S LICENSE",
  'AMER REG DX MED SONO',
  'BOC ATHLETIC TRAIN CERT',
  'SOC HUM RES MGMT-CERT PRO',
  'REG POLSOM TECH',
  'CERT PUBLIC ACCT',
  'CPR-Infant and Child',
  'LICENSED PRACTICAL NURSE',
  'ULTRASONOGRAHER']

LicenseAndCertificationCriteria_LicenseAndCertificationId = [None]

LicenseAndCertificationCriteria_Required =  ['false', 'true']

# Skills Criteria
SkillsCriteria_Name = ['Flexibility',
  'Reporting',
  'KEYBOARD SKILLS 60WPM',
  'Industry Knowledge',
  'CPT Coding',
  'KEYBOARD SKILLS 40WPM',
  'DETAIL ORIENTED',
  'Cash Handling',
  'Dependable',
  'BENEFITS',
  'Investigating',
  'Creative Thinking',
  'Presentation',
  'Infrastructure',
  'Years in Industry: 0-2',
  'Finance Loan Strategy',
  'Planning & Organizing',
  'Adaptability/Flexibility',
  'CONTINUOUS IMPROVEMENT',
  'Interviewing',
  'CALL CENTER',
  'Data Analysis',
  'Tools',
  'Empathy',
  'Technical Writing',
  'Negotiating',
  'Managerial Ability',
  'Organizing',
  'Facilities Management',
  'MANAGEMENT',
  'Portfolio Management',
  'Calculating',
  'MEDICAL TERMINOLOGY',
  'Driving',
  'AUDIO/VISUAL KNOWLEDGE',
  'ABILITY FOLLOW DIRECTIONS',
  'Compensation Mgmt',
  'Written Communication',
  'Design',
  'Research',
  'Restaurant Back of House',
  'Customer Service',
  'Risk Management',
  'Time Management',
  'Microsoft Excel',
  'Acquisition Process',
  'Technical',
  'Responsibility',
  'Excel',
  'INDEPENDENT THINKING',
  'MICROSOFT ACCESS',
  'Business Modeling',
  'Supervisory',
  'Goal Achievement',
  'Berkshire Values',
  'Helping Others',
  'Communication/CS',
  'Self-Direction',
  'Influencing',
  'ICD10',
  'Information Technology',
  'MICROSOFT EXCEL',
  'Organizational Strategies',
  'Initiative',
  'Self-Directed',
  'Spanish',
  'KNOWLEDGE CELL PHONE',
  'Productivity',
  'Writing',
  'Product Knowledge',
  'ICD-10 Coding',
  'ABILITY TO MULTI-TASK',
  'Active Listening',
  'PROFICIENT KEYBOARD SKILL',
  'Business Management',
  'Client Support',
  'Support',
  'Scheduling',
  'Years in Industry: 16-20',
  'Licenses & Certifications',
  'Analysis',
  'Goal Setting',
  'Understanding Financials in Logistics',
  'Influencing Others',
  'HR Delivery',
  'Personal Accountability',
  'Proficient on sales strategies and behaviors',
  'Organization Strategies',
  'Servers',
  'Work Environment Safety',
  'Customer Focus',
  'Effective Communication',
  'Training Confidence',
  'Read & Understand Blueprints',
  'COMMUNICATION ORAL',
  'HEALTHCARE RECRUITING',
  'Years in Industry: 6-10',
  'Creativity',
  'Interpersonal Skills',
  'DECISION MAKING ABILITY',
  'Performance',
  'Internet',
  'Learning Agility',
  'Collaborating',
  'MS Excel',
  'PROBLEM SOLVING',
  'Leading Others',
  'Planning',
  'Consultation',
  'Problem-solving',
  'Good Judgment',
  'Sense of Urgency',
  'Training',
  'Working knowledge of MS Office',
  'Motivating team builder',
  'PHLEBOTOMY',
  'PATIENT CARE',
  'Restaurant Front of House',
  'CREATIVITY',
  'Budgets/Cost Control',
  'Legal',
  'TRANSITION SMOOTHLY',
  'Troubleshooting',
  'Miscrosoft Word',
  'ICD9',
  'Basic computer skills',
  'Follow Specifications',
  'Conflict Management',
  'Administrative',
  'Analyzing',
  'Documentation',
  'Maintenance',
  'Resolves Conflict',
  'Customer Support',
  'ACCOUNTS RECEIVABLE',
  'SOUND JUDGMENT',
  'Market Community Know',
  'Judgment',
  'EXCELLENT COMMUNICATION',
  'EXCELLENT CUST SVC',
  'Quality Control',
  'Reporting and Analyzing Metrics',
  'Public Speaking',
  'MICROSOFT POWERPOINT',
  'SPEAK CLEARLY/PROFESSION',
  'Social Media',
  'Negotiation',
  'MS Word',
  'Microsoft Windows',
  'CUSTOMER SERVICE',
  'Management',
  'Self-Management',
  'Professionalism',
  'Resourceful',
  'SWITCHBOARD',
  'PAYOR/INSURANCE BENEFITS',
  'Attitude',
  'Business Intelligence',
  'Conceptual Thinking',
  'Organization Skills',
  'Microsoft Word',
  'Coordination',
  'Reliable',
  'Critical thinking',
  'Accounting Operations',
  'Working Well Under Pressure',
  'Dependability',
  'Verbal Communication',
  'MICROSOFT OFFICE',
  'Multi-Tasking',
  'Read Tape Measure to 1/16"',
  'Microsoft Office 365',
  'Presenting',
  'Problem solving',
  'Friendliness',
  'Multitasking',
  'Relationship Building',
  'Financial Analysis',
  'ORGANIZATIONAL SKILLS',
  'Positive Attitude',
  'Listening',
  'PHONE ETIQUETTE',
  'Multilingual',
  'Business Knowledge',
  'Value Creation',
  'Clerical',
  'People Development',
  'Field Presence',
  'Team Building',
  'Enthusiastic',
  'TIME MANAGEMENT',
  'Integrity',
  'Investor Management',
  'Database Design',
  'Database Management',
  'Resolution',
  'Data',
  'FLEXIBILITY',
  'Graphic Design',
  'Analytical Concept Thinkg',
  'Emotional Intelligence',
  'Coaching',
  'Financial Reporting',
  'Team Oriented',
  'Investor Relations',
  '10 KEY',
  'Quality Assurance',
  'MICROSOFT OUTLOOK',
  'SQL',
  'Admin / Financial',
  'Property Management',
  'BASIC MATH',
  'PROFICIENT SPELLING',
  'Interpersonal',
  'People Management',
  'Auditing',
  'Compliance Management',
  'Self-Motivated',
  'Financial',
  'American Sign Language',
  'Finance',
  'Directing Others',
  'Issue Resolution',
  'PRIORITIZE ASSIGNMENTS',
  'Communication',
  'ORAL/WRITTEN COMMUNICATIO',
  'Excellent Oral & Written Communication',
  'KNOW CODES/REGULATIONS',
  'MS Powerpoint',
  'Microsoft Outlook',
  'Problem Solving Ability',
  'Organized while focusing on work quality',
  'Data collection',
  'Content Managment',
  'LEADERSHIP',
  'Bilingual',
  'Operational Excellence',
  'Math',
  'EPIC',
  'English',
  'Solution Delivery',
  'LEAN',
  'GE/IDX',
  'COPIER',
  'Operating Models',
  'HR Management',
  'Achievement',
  'Posses logistics enviromental dynamics',
  'Networking',
  'PROJECT PLANNING',
  'ACCOUNTING',
  'Compiling Statistics',
  'Deductive Reasoning',
  'Organization of Work',
  'Software',
  'Analytics',
  'VITALS/BP/TEMPERATURE',
  'Detail Oriented',
  'Good Judgement',
  'ELECTRONIC MEDICAL RECORD',
  'FAX MACHINE',
  'People',
  'Classifying',
  'C++',
  'Team Management',
  'Marketing',
  'Computer',
  'Years in Industry: 3-5',
  'Self-motivation',
  'Commitment',
  'Results Oriented',
  'INTERPERSONAL RELATIONSH',
  'ANALYSIS',
  'Problem Solving',
  'Financial Analysis Report',
  'CODING',
  'CPT',
  'Project Management',
  'Microsoft Execl',
  'Effective Negotiation Skills',
  'Installation',
  'Pediatric',
  'Development',
  'HEALTHCARE BILLING',
  'Financial Management',
  'Bilingual - Spanish',
  'Results Focus',
  'Relationship Management',
  'Data Analytics',
  'Help Desk',
  'Employee Relations',
  'Systems Administration',
  'Team Player',
  'Presentations',
  'Microsoft Office Suite',
  'Budgeting',
  'General Business Practices',
  'COMMUNICATION WRITTEN',
  'Administration',
  'Collaboration',
  'BASIC OFFICE/COMPUTERS',
  'Maintenanace Management',
  'WORK IN TEAM ENVIRONMENT',
  'Forecasting',
  'Presentation Skills',
  'Oral Communication',
  'Years in Industry: 11-15',
  'Teamwork',
  'Critical Thinking',
  'Personal Organization',
  'Analytical',
  'Accountability',
  'Operations',
  'Decision Making Judgment',
  'Planning and Organizing',
  'Microsoft Office',
  'Content Strategy',
  'Attention to Detail',
  'Checking for Accuracy',
  'Team Leadership',
  'Sales',
  'Self-Motivation',
  'Decision Making',
  'Courteous',
  'Leadership',
  'Document',
  'Computers / Technical',
  'Business Development',
  'Mechanical',
  'Applications',
  'Recruiting']

SkillsCriteria_MinimumScaleValue = ['5', '4', '1', '3', '2']
SkillsCriteria_MinimumScaleValueName = ['Advanced',
  'Expert',
  'Novice',
  'Intermediate',
  'Some Knowledge']

SkillsCriteria_Required = ['false', 'true']
skills_scalevalue_dict = {'5': "Advanced", '4':"Expert", '1': "Novice", '3': "Intermediate", '2': "Some Knowledge"}

# Work Experiences
WorkExperiences_StartMonth = [None] + list(range(1,13,1))
WorkExperiences_EndMonth = [None] + list(range(1,13,1))
WorkExperiences_StartYear = [None] + list(range(1945,2024,1))
WorkExperiences_EndYear = [None] + list(range(1945,2024,1))
 
Education_StartMonth = [None] + list(range(1,13,1))
Education_EndMonth = [None] + list(range(1,13,1))
Education_StartYear = [None] + list(range(1945,2024,1))
Education_EndYear = [None] + list(range(1945,2024,1))
 
# Education
#No lists to display

# Licensing and Certifications
LicenseAndCertification_Active = [False, True]
LicenseAndCertification_Awarded = [None]
LicenseAndCertification_RenewalDate = [None]

# Skills
Skills = ['4', '2', '5', '1', '3']

# Motivations
Motivation_Name = ['Job Security',
 'Peer Recognition',
 'Goal Completion',
 'Growth Opportunities',
 'Entrepreneurial Spirit',
 'Flexibility',
 'Ability to Make an Impact',
 'Work-Life Balance',
 'Financial',
 'Self-Starter']

Motivation_Description = ['Inspired to perform well by monetary reimbursement',
 'Inspired to perform well by having ample time to pursue work and interests outside of work',
 'Inspired to perform well by the knowledge that your job is safe',
 'Inspired to perform well by the praise of coworkers',
 'Inspired to perform well when granted the ability to set your own schedule and goals',
 'Inspired to perform without outside help',
 'Inspired to perform well by the ability to contribute to the success of a project or the organization',
 'Inspired to perform well by the chance to take on more responsibility',
 'Inspired to perform well by the completion of tasks',
 'Inspired to perform well by an ability to drive new ventures within the business']

# Behaviors
Behavior_Description = ['Considered a thought leader on a subject',
 'Shows firm and constant support to a cause',
 'Devoted to a task or purpose with loyalty or integrity',
 'Capable of carrying out a given task with all details necessary to get the task done well',
 'Shows intense and eager enjoyment and interest',
 'Consistently introduces new ideas and demonstrates original thinking',
 'Works well as a member of a group',
 'Capable of making others think deeply on a subject',
 'Inspires teammates to follow them']


Behavior_Name = ['Team Player',
 'Innovative',
 'Functional Expert',
 'Detail Oriented',
 'Loyal',
 'Leader',
 'Thought Provoking',
 'Dedicated',
 'Enthusiastic']

Step_Name = ['Offer Approval',
 'Background Ck - Crim & MVR',
 'Post-offer Drug Screen',
 'Reviewed - Not Interested',
 'Not Qualified',
 'Phone Screening/Interview',
 'Interview - 1',
 'Do Not Hire',
 'Offer Letter and Job Description',
 'Ready for Interview',
 'Over Qualified',
 'Offer Withdrawn',
 'Review',
 'References in Progress',
 'Post-offer Physical & Drug Screen',
 'Phone Screen',
 'Offer Letter & Job Description',
 '1st Interview',
 'Pre-Hire Employment Checks',
 'Recruiter Review',
 'In Person Interview #1',
 'Focused Interview',
 'Pre-Employment Checks',
 'Reviewed - Considered for other job',
 'Hiring Manager Review',
 'References In Process',
 'Video Interview',
 'Job Offer',
 'In-Person Interview #1',
 'Post Offer / Physical & Drug Screen',
 'Background Check (Criminal & MVR)',
 'Screening in progress',
 'Qualified but not a Match',
 'Reference Check',
 'Second Interview',
 'Offer',
 'Schedule Interview',
 'Interviewing for another Excela Health position',
 '2nd  Interview',
 'Screening in Process',
 'Process Offer',
 'Incomplete',
 'Extend Contingent Offer',
 'Phone Screen - 1',
 '2nd Interview',
 'Reference Interview',
 'Sent for Drug Screen',
 'In Person Interview2',
 'In process with another manager',
 'Assessment Completed',
 'In Review',
 'In Person Interview1',
 'Video or Onsite Interview 1',
 'Not Interested',
 'Assessment Requested',
 'Being Reviewed',
 'Considered for Another Job',
 'Offer made',
 'Background Check',
 'Not Qualifed',
 'Phone Screen: Hiring Manager',
 'Selected Another Candidate',
 'Reference Checks',
 'In Person Interview 2',
 'Not Selected',
 'Final Candidate',
 'Declined',
 'Screen',
 '3rd Interview',
 'Post-Offer Phys and/or Drug Screen',
 'Contingent Offer',
 'Background Screen',
 'Phone Interview',
 'Conditional Job Offer',
 'Phone Screen - Hiring Manager',
 'Pre-Interview Assessments',
 'In Person Interview',
 'Considered for another Position',
 'Offer Declined',
 'Hire',
 'Initiate Background Check',
 'Decline After Interview',
 'Declne',
 'Phone Screen/Interview',
 'Interview',
 'Interview  - 2',
 'Phone Screen_1',
 'Phone Screen / Interview',
 'Send WOTC Email',
 'Background Check Started',
 'Assessments Requested',
 'Make Offer',
 'In Person Interview #2',
 'Topgrading Interview',
 'In-Person Interview',
 'Draft Contingent Offer Letter',
 'In Person Interview 1',
 'Manager Interview',
 'Recruiter Interview',
 'Decline',
 'Hired',
 'Not in Consideration',
 'Assessments Completed',
 'Offer Extended',
 'Under Qualified',
 'First Interview',
 'Phone Screen: Recruiter',
 'Onsite Interview',
 'Interviewed',
 'Resume Screening',
 'Recruiter Reviewed']

############ Tag
Tag = [1.0, 2.0, 3.0, 4.0 ,5.0, 6.0]

############ StepGroup
Step_Group = ['Background_Check', 'Declined', 'Hired', 'Interview', 'Other',
 'References',
 'Screen']

########### Pass_first_step
Pass_First_Step = [False, True]

########## 

# Defining list of column names that contains the names of the columns, if they belong to the job or candidate

job_column = ['ExternalBriefDescription','ExternalDescription', 'Title', 
              'JobCategoryName']
uid_column = ['OpportunityId', 'ApplicationId']
can_column = [
    'IsCandidateInternal',
    'BehaviorCriteria', 
    'MotivationCriteria',
    'EducationCriteria', 
    'LicenseAndCertificationCriteria', 
    'SkillCriteria', 
    'WorkExperiences', 
    'Educations', 
    'LicenseAndCertifications', 
    'Skills', 'Motivations', 
    'Behaviors', 
    'StepName', 
    'Tag', 
    'StepGroup',
    'pass_first_step'
  ] # Column - StepId has been removed
sel_column = ['IsRejected']

# Defining list of columns based on the type of contents

str_column = [
    'ExternalBriefDescription', 
    'ExternalDescription', 
    'Title', 
    'JobCategoryName', 
    'BehaviorCriteria', 
    'MotivationCriteria', 
    'EducationCriteria', 
    'LicenseAndCertificationCriteria', 
    'SkillCriteria', 
    'WorkExperiences', 
    'Educations', 
    'LicenseAndCertifications', 
    'Skills', 
    'Motivations', 
    'Behaviors', 
    'StepId', 
    'StepName', 
    'StepGroup'
]
bool_column = ['IsCandidateInternal', 'pass_first_step']
float_column = ['Tag']

# Defining list of columns based on the models

model_names = ["w2v", "bert", "dbert"]